AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Music Generation Function Only

Globals:
  Function:
    Runtime: python3.13
    Architectures:
      - arm64
    Timeout: 120
    MemorySize: 1024

Resources:
  # Use existing resources
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowOrigins:
          - '*'

  MusicGenerationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.13
      Handler: app.lambda_handler
      CodeUri: functions/music-generation/
      Timeout: 120
      MemorySize: 1024
      Environment:
        Variables:
          BUCKET_NAME: hackathon-demo-imageuploadbucket-1234567890
          TABLE_NAME: hackathon-demo-DataTable-1GXOJ0HMUT9BJ
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:Query
              Resource: arn:aws:dynamodb:us-east-1:*:table/hackathon-demo-DataTable-1GXOJ0HMUT9BJ
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: arn:aws:s3:::hackathon-demo-imageuploadbucket-*/*
      Events:
        GenerateMusic:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/music/generate
            Method: post

Outputs:
  ApiUrl:
    Description: HTTP API endpoint URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'