AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hackathon backend infrastructure

Metadata:
  esbuild-properties: &esbuild-properties
    Format: esm
    Minify: false
    OutExtension:
      - .js=.mjs
    Target: es2020
    Sourcemap: false
    EntryPoints:
      - index.mjs
    Banner:
      - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
    External:
      - "@aws-sdk/*"
    Loader: []

Globals:
  Function:
    CodeUri: functions
    Architectures:
      - arm64
    Tracing: Active
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
        TABLE_NAME: !Ref DataTable

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowOrigins:
          - '*'

  # DynamoDB table for egg quality data
  DataTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  # S3 Bucket for image uploads (used for both general uploads and egg analysis)
  ImageUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-image-uploads-${AWS::AccountId}'
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: ['*']
            AllowedMethods: [PUT, POST]
            AllowedHeaders: ['*']
            MaxAge: 3000
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  GeneratePresignedUrlFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - generate-presigned-url.mjs
    Properties:
      Runtime: nodejs22.x
      Handler: generate-presigned-url.handler
      CodeUri: functions/image-upload/
      Environment:
        Variables:
          BUCKET_NAME: !Ref ImageUploadBucket
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectAcl
              Resource: !Sub '${ImageUploadBucket.Arn}/*'
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /upload/presigned-url
            Method: post

  # EventBridge rule to trigger Lambda on S3 object creation
  ImageUploadRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Trigger image processor when egg images are uploaded to S3
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref ImageUploadBucket
      State: ENABLED
      Targets:
        - Arn: !GetAtt ImageProcessorFunction.Arn
          Id: ImageProcessorTarget

  # Permission for EventBridge to invoke Image Processor Lambda
  ImageProcessorEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ImageProcessorFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ImageUploadRule.Arn

  # Image Processor Lambda function
  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - index.mjs
    Properties:
      Runtime: nodejs22.x
      Handler: index.handler
      CodeUri: functions/imageProcessor/
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          BUCKET_NAME: !Ref ImageUploadBucket
          BEDROCK_AGENT_ID: placeholder
          BEDROCK_AGENT_ALIAS_ID: placeholder
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ImageUploadBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeAgent
              Resource: !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/*'
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'

  # Egg Data Tool Lambda function
  EggDataToolFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - index.mjs
    Properties:
      Runtime: nodejs22.x
      Handler: index.handler
      CodeUri: functions/eggDataTool/
      Timeout: 60
      MemorySize: 256
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataTable
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'

Outputs:
  ApiUrl:
    Description: HTTP API endpoint URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'
  TableName:
    Description: DynamoDB table name
    Value: !Ref DataTable
  ImageUploadBucketName:
    Description: S3 bucket for image uploads (used for egg analysis)
    Value: !Ref ImageUploadBucket
  ImageProcessorFunctionArn:
    Description: Image Processor Lambda function ARN
    Value: !GetAtt ImageProcessorFunction.Arn
  EggDataToolFunctionArn:
    Description: Egg Data Tool Lambda function ARN
    Value: !GetAtt EggDataToolFunction.Arn
