import boto3
import json
import os
from datetime import datetime
from decimal import Decimal

dynamodb = boto3.resource('dynamodb')
table_name = os.environ.get('TABLE_NAME', 'hackathon-demo-DataTable')
table = dynamodb.Table(table_name)

trees = [
    {
        "id": "tree-001",
        "vendorName": "Texas Tree Co",
        "treeName": "Premium Fraser Fir",
        "treeType": "real",
        "height": 7,
        "price": 89,
        "qualityRating": 4.8,
        "imageUrl": "https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400",
        "deliveryZones": ["North Texas", "Central Texas"],
        "deliveryFee": 25,
        "returnWindowDays": 14,
        "socialPopularityScore": 85,
        "socialMentions": 1200,
        "description": "Beautiful Fraser Fir with excellent needle retention",
        "specifications": {"width": 4.5, "needleType": "Fraser Fir"},
        "inStock": True
    },
    {
        "id": "tree-002",
        "vendorName": "Holiday Trees TX",
        "treeName": "Noble Fir Deluxe",
        "treeType": "real",
        "height": 8,
        "price": 125,
        "qualityRating": 4.9,
        "imageUrl": "https://images.unsplash.com/photo-1543589077-47d81606c1bf?w=400",
        "deliveryZones": ["North Texas", "Central Texas", "South Texas"],
        "deliveryFee": 30,
        "returnWindowDays": 30,
        "socialPopularityScore": 92,
        "socialMentions": 2500,
        "description": "Top-rated Noble Fir with strong branches",
        "specifications": {"width": 5, "needleType": "Noble Fir"},
        "inStock": True
    },
    {
        "id": "tree-003",
        "vendorName": "Budget Trees",
        "treeName": "Classic Pine",
        "treeType": "real",
        "height": 6,
        "price": 45,
        "qualityRating": 3.8,
        "imageUrl": "https://images.unsplash.com/photo-1576097449798-7c7f90e1248a?w=400",
        "deliveryZones": ["North Texas"],
        "deliveryFee": 15,
        "returnWindowDays": 7,
        "socialPopularityScore": 45,
        "socialMentions": 300,
        "description": "Affordable pine tree for budget-conscious families",
        "specifications": {"width": 3.5, "needleType": "Pine"},
        "inStock": True
    },
    {
        "id": "tree-004",
        "vendorName": "Evergreen Elegance",
        "treeName": "Pre-Lit Artificial Spruce",
        "treeType": "artificial",
        "height": 7.5,
        "price": 299,
        "qualityRating": 4.7,
        "imageUrl": "https://images.unsplash.com/photo-1606297090426-8a6d36e3f3e8?w=400",
        "deliveryZones": ["North Texas", "Central Texas", "South Texas", "West Texas"],
        "deliveryFee": 0,
        "returnWindowDays": 30,
        "socialPopularityScore": 78,
        "socialMentions": 950,
        "description": "Premium artificial tree with 1000 LED lights",
        "specifications": {"width": 5, "lightCount": 1000, "material": "PE/PVC"},
        "inStock": True
    },
    {
        "id": "tree-005",
        "vendorName": "Texas Tree Co",
        "treeName": "Douglas Fir Classic",
        "treeType": "real",
        "height": 6.5,
        "price": 75,
        "qualityRating": 4.5,
        "imageUrl": "https://images.unsplash.com/photo-1544986581-efac024faf62?w=400",
        "deliveryZones": ["North Texas", "Central Texas"],
        "deliveryFee": 20,
        "returnWindowDays": 14,
        "socialPopularityScore": 68,
        "socialMentions": 780,
        "description": "Traditional Douglas Fir with great fragrance",
        "specifications": {"width": 4, "needleType": "Douglas Fir"},
        "inStock": True
    },
    {
        "id": "tree-006",
        "vendorName": "Premium Pines",
        "treeName": "Grand Fir Supreme",
        "treeType": "real",
        "height": 9,
        "price": 185,
        "qualityRating": 5.0,
        "imageUrl": "https://images.unsplash.com/photo-1512389098783-66b81f86e199?w=400",
        "deliveryZones": ["North Texas", "Central Texas"],
        "deliveryFee": 40,
        "returnWindowDays": 30,
        "socialPopularityScore": 95,
        "socialMentions": 3200,
        "description": "Stunning 9-foot Grand Fir, perfect for high ceilings",
        "specifications": {"width": 6, "needleType": "Grand Fir"},
        "inStock": True
    },
    {
        "id": "tree-007",
        "vendorName": "Artificial Wonders",
        "treeName": "Slim Artificial Pine",
        "treeType": "artificial",
        "height": 7,
        "price": 149,
        "qualityRating": 4.3,
        "imageUrl": "https://images.unsplash.com/photo-1576097449798-7c7f90e1248a?w=400",
        "deliveryZones": ["North Texas", "Central Texas", "South Texas"],
        "deliveryFee": 0,
        "returnWindowDays": 30,
        "socialPopularityScore": 62,
        "socialMentions": 520,
        "description": "Space-saving slim design, perfect for apartments",
        "specifications": {"width": 3, "lightCount": 500, "material": "PVC"},
        "inStock": True
    },
    {
        "id": "tree-008",
        "vendorName": "Budget Trees",
        "treeName": "Economy Spruce",
        "treeType": "real",
        "height": 5,
        "price": 35,
        "qualityRating": 3.5,
        "imageUrl": "https://images.unsplash.com/photo-1543589077-47d81606c1bf?w=400",
        "deliveryZones": ["North Texas"],
        "deliveryFee": 10,
        "returnWindowDays": 7,
        "socialPopularityScore": 38,
        "socialMentions": 180,
        "description": "Basic spruce tree at an unbeatable price",
        "specifications": {"width": 3, "needleType": "Spruce"},
        "inStock": True
    },
    {
        "id": "tree-009",
        "vendorName": "Holiday Trees TX",
        "treeName": "Balsam Fir Premium",
        "treeType": "real",
        "height": 7,
        "price": 95,
        "qualityRating": 4.6,
        "imageUrl": "https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400",
        "deliveryZones": ["North Texas", "Central Texas", "South Texas"],
        "deliveryFee": 25,
        "returnWindowDays": 21,
        "socialPopularityScore": 72,
        "socialMentions": 890,
        "description": "Fragrant Balsam Fir with dark green needles",
        "specifications": {"width": 4.5, "needleType": "Balsam Fir"},
        "inStock": True
    },
    {
        "id": "tree-010",
        "vendorName": "Evergreen Elegance",
        "treeName": "Flocked Artificial Tree",
        "treeType": "artificial",
        "height": 6.5,
        "price": 249,
        "qualityRating": 4.8,
        "imageUrl": "https://images.unsplash.com/photo-1606297090426-8a6d36e3f3e8?w=400",
        "deliveryZones": ["North Texas", "Central Texas", "South Texas", "West Texas"],
        "deliveryFee": 0,
        "returnWindowDays": 30,
        "socialPopularityScore": 88,
        "socialMentions": 1850,
        "description": "Snowy flocked tree with warm white lights",
        "specifications": {"width": 4.5, "lightCount": 800, "material": "PE"},
        "inStock": True
    },
    {
        "id": "tree-011",
        "vendorName": "Texas Tree Co",
        "treeName": "Scotch Pine Traditional",
        "treeType": "real",
        "height": 6,
        "price": 65,
        "qualityRating": 4.2,
        "imageUrl": "https://images.unsplash.com/photo-1544986581-efac024faf62?w=400",
        "deliveryZones": ["North Texas", "Central Texas"],
        "deliveryFee": 20,
        "returnWindowDays": 14,
        "socialPopularityScore": 55,
        "socialMentions": 420,
        "description": "Classic Scotch Pine with sturdy branches",
        "specifications": {"width": 4, "needleType": "Scotch Pine"},
        "inStock": True
    },
    {
        "id": "tree-012",
        "vendorName": "Premium Pines",
        "treeName": "Blue Spruce Majestic",
        "treeType": "real",
        "height": 8,
        "price": 165,
        "qualityRating": 4.9,
        "imageUrl": "https://images.unsplash.com/photo-1512389098783-66b81f86e199?w=400",
        "deliveryZones": ["North Texas", "Central Texas"],
        "deliveryFee": 35,
        "returnWindowDays": 30,
        "socialPopularityScore": 90,
        "socialMentions": 2100,
        "description": "Stunning blue-tinted spruce with excellent shape",
        "specifications": {"width": 5.5, "needleType": "Blue Spruce"},
        "inStock": True
    },
    {
        "id": "tree-013",
        "vendorName": "Artificial Wonders",
        "treeName": "Pencil Slim Artificial",
        "treeType": "artificial",
        "height": 9,
        "price": 199,
        "qualityRating": 4.4,
        "imageUrl": "https://images.unsplash.com/photo-1576097449798-7c7f90e1248a?w=400",
        "deliveryZones": ["North Texas", "Central Texas", "South Texas", "West Texas"],
        "deliveryFee": 0,
        "returnWindowDays": 30,
        "socialPopularityScore": 70,
        "socialMentions": 680,
        "description": "Ultra-slim 9-foot tree for narrow spaces",
        "specifications": {"width": 2.5, "lightCount": 600, "material": "PVC"},
        "inStock": True
    },
    {
        "id": "tree-014",
        "vendorName": "Holiday Trees TX",
        "treeName": "White Pine Elegant",
        "treeType": "real",
        "height": 7.5,
        "price": 110,
        "qualityRating": 4.7,
        "imageUrl": "https://images.unsplash.com/photo-1543589077-47d81606c1bf?w=400",
        "deliveryZones": ["North Texas", "Central Texas", "South Texas"],
        "deliveryFee": 28,
        "returnWindowDays": 21,
        "socialPopularityScore": 76,
        "socialMentions": 1050,
        "description": "Soft-needled White Pine with graceful appearance",
        "specifications": {"width": 5, "needleType": "White Pine"},
        "inStock": True
    },
    {
        "id": "tree-015",
        "vendorName": "Budget Trees",
        "treeName": "Tabletop Pine",
        "treeType": "real",
        "height": 3,
        "price": 25,
        "qualityRating": 3.9,
        "imageUrl": "https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400",
        "deliveryZones": ["North Texas", "Central Texas"],
        "deliveryFee": 10,
        "returnWindowDays": 7,
        "socialPopularityScore": 42,
        "socialMentions": 250,
        "description": "Cute tabletop tree for small spaces",
        "specifications": {"width": 2, "needleType": "Pine"},
        "inStock": True
    },
    {
        "id": "tree-016",
        "vendorName": "Evergreen Elegance",
        "treeName": "Grand Artificial Fir",
        "treeType": "artificial",
        "height": 8,
        "price": 349,
        "qualityRating": 4.9,
        "imageUrl": "https://images.unsplash.com/photo-1606297090426-8a6d36e3f3e8?w=400",
        "deliveryZones": ["North Texas", "Central Texas", "South Texas", "West Texas"],
        "deliveryFee": 0,
        "returnWindowDays": 30,
        "socialPopularityScore": 93,
        "socialMentions": 2800,
        "description": "Luxury artificial tree with realistic PE needles",
        "specifications": {"width": 5.5, "lightCount": 1200, "material": "PE"},
        "inStock": True
    },
    {
        "id": "tree-017",
        "vendorName": "Texas Tree Co",
        "treeName": "Nordmann Fir Premium",
        "treeType": "real",
        "height": 7,
        "price": 135,
        "qualityRating": 4.8,
        "imageUrl": "https://images.unsplash.com/photo-1544986581-efac024faf62?w=400",
        "deliveryZones": ["North Texas", "Central Texas"],
        "deliveryFee": 30,
        "returnWindowDays": 21,
        "socialPopularityScore": 82,
        "socialMentions": 1400,
        "description": "Premium Nordmann Fir with soft needles",
        "specifications": {"width": 4.5, "needleType": "Nordmann Fir"},
        "inStock": True
    },
    {
        "id": "tree-018",
        "vendorName": "Premium Pines",
        "treeName": "Concolor Fir Deluxe",
        "treeType": "real",
        "height": 8.5,
        "price": 175,
        "qualityRating": 4.9,
        "imageUrl": "https://images.unsplash.com/photo-1512389098783-66b81f86e199?w=400",
        "deliveryZones": ["North Texas", "Central Texas"],
        "deliveryFee": 38,
        "returnWindowDays": 30,
        "socialPopularityScore": 87,
        "socialMentions": 1900,
        "description": "Beautiful Concolor Fir with citrus scent",
        "specifications": {"width": 5.5, "needleType": "Concolor Fir"},
        "inStock": True
    },
    {
        "id": "tree-019",
        "vendorName": "Artificial Wonders",
        "treeName": "Color-Changing LED Tree",
        "treeType": "artificial",
        "height": 7,
        "price": 279,
        "qualityRating": 4.6,
        "imageUrl": "https://images.unsplash.com/photo-1576097449798-7c7f90e1248a?w=400",
        "deliveryZones": ["North Texas", "Central Texas", "South Texas", "West Texas"],
        "deliveryFee": 0,
        "returnWindowDays": 30,
        "socialPopularityScore": 85,
        "socialMentions": 1650,
        "description": "Modern tree with app-controlled color-changing lights",
        "specifications": {"width": 4.5, "lightCount": 900, "material": "PE/PVC"},
        "inStock": True
    },
    {
        "id": "tree-020",
        "vendorName": "Holiday Trees TX",
        "treeName": "Fraser Fir Compact",
        "treeType": "real",
        "height": 5.5,
        "price": 70,
        "qualityRating": 4.4,
        "imageUrl": "https://images.unsplash.com/photo-1543589077-47d81606c1bf?w=400",
        "deliveryZones": ["North Texas", "Central Texas", "South Texas"],
        "deliveryFee": 18,
        "returnWindowDays": 14,
        "socialPopularityScore": 58,
        "socialMentions": 480,
        "description": "Compact Fraser Fir perfect for smaller rooms",
        "specifications": {"width": 3.5, "needleType": "Fraser Fir"},
        "inStock": True
    },
    {
        "id": "tree-021",
        "vendorName": "Budget Trees",
        "treeName": "Basic Artificial Pine",
        "treeType": "artificial",
        "height": 6,
        "price": 79,
        "qualityRating": 3.7,
        "imageUrl": "https://images.unsplash.com/photo-1606297090426-8a6d36e3f3e8?w=400",
        "deliveryZones": ["North Texas", "Central Texas"],
        "deliveryFee": 0,
        "returnWindowDays": 14,
        "socialPopularityScore": 48,
        "socialMentions": 320,
        "description": "Affordable artificial tree for budget shoppers",
        "specifications": {"width": 4, "lightCount": 300, "material": "PVC"},
        "inStock": True
    },
    {
        "id": "tree-022",
        "vendorName": "Evergreen Elegance",
        "treeName": "Snowy Mountain Pine",
        "treeType": "artificial",
        "height": 7.5,
        "price": 319,
        "qualityRating": 4.8,
        "imageUrl": "https://images.unsplash.com/photo-1576097449798-7c7f90e1248a?w=400",
        "deliveryZones": ["North Texas", "Central Texas", "South Texas", "West Texas"],
        "deliveryFee": 0,
        "returnWindowDays": 30,
        "socialPopularityScore": 91,
        "socialMentions": 2400,
        "description": "Heavily flocked tree with realistic snow effect",
        "specifications": {"width": 5, "lightCount": 1000, "material": "PE"},
        "inStock": True
    },
    {
        "id": "tree-023",
        "vendorName": "Texas Tree Co",
        "treeName": "Leyland Cypress",
        "treeType": "real",
        "height": 6.5,
        "price": 55,
        "qualityRating": 4.0,
        "imageUrl": "https://images.unsplash.com/photo-1544986581-efac024faf62?w=400",
        "deliveryZones": ["North Texas", "Central Texas", "South Texas"],
        "deliveryFee": 18,
        "returnWindowDays": 14,
        "socialPopularityScore": 52,
        "socialMentions": 380,
        "description": "Texas-grown Leyland Cypress with full shape",
        "specifications": {"width": 4, "needleType": "Cypress"},
        "inStock": True
    },
    {
        "id": "tree-024",
        "vendorName": "Premium Pines",
        "treeName": "Turkish Fir Luxury",
        "treeType": "real",
        "height": 9,
        "price": 225,
        "qualityRating": 5.0,
        "imageUrl": "https://images.unsplash.com/photo-1512389098783-66b81f86e199?w=400",
        "deliveryZones": ["North Texas", "Central Texas"],
        "deliveryFee": 45,
        "returnWindowDays": 30,
        "socialPopularityScore": 96,
        "socialMentions": 3500,
        "description": "Rare Turkish Fir with exceptional needle retention",
        "specifications": {"width": 6, "needleType": "Turkish Fir"},
        "inStock": True
    },
    {
        "id": "tree-025",
        "vendorName": "Artificial Wonders",
        "treeName": "Frosted Alpine Spruce",
        "treeType": "artificial",
        "height": 6.5,
        "price": 189,
        "qualityRating": 4.5,
        "imageUrl": "https://images.unsplash.com/photo-1606297090426-8a6d36e3f3e8?w=400",
        "deliveryZones": ["North Texas", "Central Texas", "South Texas", "West Texas"],
        "deliveryFee": 0,
        "returnWindowDays": 30,
        "socialPopularityScore": 74,
        "socialMentions": 920,
        "description": "Frosted tips create a winter wonderland look",
        "specifications": {"width": 4.5, "lightCount": 700, "material": "PE/PVC"},
        "inStock": True
    }
]

def seed_data():
    now = datetime.now().isoformat()
    
    for tree in trees:
        item = {
            "pk": "TREE",
            "sk": f"TREE#{tree['id']}",
            "vendorId": f"vendor-{hash(tree['vendorName']) % 100}",
            "createdAt": now,
            "updatedAt": now,
            **tree
        }
        
        # Convert floats to Decimal for DynamoDB
        item['price'] = Decimal(str(item['price']))
        item['qualityRating'] = Decimal(str(item['qualityRating']))
        item['deliveryFee'] = Decimal(str(item['deliveryFee']))
        item['socialPopularityScore'] = Decimal(str(item['socialPopularityScore']))
        item['specifications']['width'] = Decimal(str(item['specifications']['width']))
        if 'lightCount' in item['specifications']:
            item['specifications']['lightCount'] = Decimal(str(item['specifications']['lightCount']))
        
        # Add deliveryZone for GSI (use first zone)
        item['deliveryZone'] = tree['deliveryZones'][0]
        
        table.put_item(Item=item)
        print(f"Added tree: {tree['treeName']}")
    
    print(f"\nSuccessfully seeded {len(trees)} trees!")

if __name__ == "__main__":
    seed_data()
